name: Bedrock
version: ${project.version}
main: me.ufo.bedrock.Bedrock
depend: [Architect]
commands:
  combat:
    aliases: [ct]
  setspawn:
  tp:
  tploc:
  tptoggle:
  tpoffline:
  tpall:
  tpa:
  tpahere:
  tpaall:
  tpacancel:
  tpaccept:
    aliases: [tpyes]
  tpdeny:
